# Build the binary release version for Mac

name: Update binary release names and links in the doc

on:
  repository_dispatch:
    types: [node-released]

jobs:
  node-released:
    runs-on: ubuntu-22.04
    permissions:
      contents: write
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
      - name: Run the update script
        run: |
          chmod +x update-release-link.sh
          ./update-release-link.sh \
              "${{ github.event.client_payload.release-version }}" \
              "${{ github.event.client_payload.mac-link-dymension }}" \
              "${{ github.event.client_payload.mac-link-near }}" \
              "${{ github.event.client_payload.mac-link-kasplex }}" \
              "${{ github.event.client_payload.windows-download-link-dymension }}" \
              "${{ github.event.client_payload.windows-preview-link-dymension }}" \
              "${{ github.event.client_payload.windows-download-link-near }}" \
              "${{ github.event.client_payload.windows-preview-link-near }}" \
              "${{ github.event.client_payload.windows-download-link-kasplex }}" \
              "${{ github.event.client_payload.windows-preview-link-kasplex }}"
      - name: Commit the changes
        uses: EndBug/add-and-commit@v9
        with:
          author_name: "GitHub Action"
          author_email: "hi@crynux.ai"
          message: "Update node release to ${{ github.event.client_payload.release-version }}"
